#!/bin/sh -e

docker ps -q | xargs docker inspect -f '{{.NetworkSettings.IPAddress}} {{ .Config.Hostname }}' | sudo tee /etc/hosts.d/20-docker.conf > /dev/null

echo " + Refreshing /etc/hosts/20-docker.conf..."
echo "";
cat /etc/hosts.d/*.conf | sudo tee /etc/hosts
