#!/bin/sh -e

docker ps -q | xargs docker inspect -f '{{.NetworkSettings.IPAddress}} {{ .Config.Hostname }}' | sudo tee /etc/hosts.d/20-docker.conf > /dev/null
docker ps -q | xargs docker inspect -f '{{.NetworkSettings.IPAddress}} {{ .Config.Hostname }}.dev' | sudo tee -a /etc/hosts.d/20-docker.conf > /dev/null

echo -e "\e[0;32m + Refreshing /etc/hosts...\e[0m"
echo "";

if [[ -a /etc/hosts ]]; then
    sudo rm /etc/hosts
fi
for FILE in /etc/hosts.d/*.conf; do
    echo "# $FILE" | sudo tee -a /etc/hosts
    cat $FILE | sudo tee -a /etc/hosts
    echo "" | sudo tee -a /etc/hosts
done;
